### ISSUE TITLE
Feature added to TYPO3 core

### ISSUE THREAD

**Issue by derhansen** [creifenscheid/rte_ckeditor_textpartlanguage#3]
Note: This extension has become superfluous with https://forge.typo3.org/issues/101128 (included in TYPO3 12.4.8+), since the CKEditor 5 language plugin is included in TYPO3 core.

**Comment by creifenscheid** [comment]
Great news!

Thank you for the note, I really appreciate it! I will set the max version for the core requirement accordingly and include the note in the README file.

**Comment by derhansen** [comment]
Thanks a lot. 

For the records - CKEditor YAML configuration for Core Language plugin:

```
editor:
  config:
    importModules:
      - { module: '@ckeditor/ckeditor5-language', exports: [ 'TextPartLanguage' ] }

    toolbar:
      items:
        - textPartLanguage

    language:
      textPartLanguage:
        - { title: 'Englisch', languageCode: 'en' }
        - { title: 'Arabic', languageCode: 'ar' }
```
